### ISSUE TITLE
Abstract classes for OfferSet and Offer

### ISSUE THREAD

**Issue by Zarquan** [Zarquan/ExecutionPlanner#98]
Add Abstract classes for OfferSet and ExecutionSession that extend AbstractComponent, with derived classes for the initial versions.
```
AbstractOfferSet:
  type: object
  required:
    - type
  discriminator:
    propertyName: type
    mapping:
      'urn:ivoa-offerset-0.1': 'IvoaOfferSet01'
    allOf:
      - $ref: 'AbstractComponent'
      - type: object
        properties:
          ....
          ....
```

This adds a type uri to OfferSet and ExecutionSession, leaving us space to have different versions in future.

```
AbstractOfferSet:
  type: object
  required:
    - type
  discriminator:
    propertyName: type
    mapping:
      'urn:ivoa-offerset-0.1': 'IvoaOfferSet01'
      'urn:ivoa-offerset-0.2': 'IvoaOfferSet02'
    allOf:
      - $ref: 'AbstractComponent'
      - type: object
        properties:
          ....
          ....
```

Same for ExecutionSession.
